# Embeddings

In [1]:
import os
import sys

sys.path.insert(0, os.path.abspath("../src"))

In [2]:
from embeddings.vectorizers import (
    build_char_ngrams,
    build_ngram_vectorizer,
    build_tfidf,
)

## 1.   vectorization

#### a.   Bag of Words (BoW)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "the delivery was slow",
    "the product quality is great",
    "delivery delivery delivery was fast",
]

vectorizer = CountVectorizer()
vecteurs = vectorizer.fit_transform(documents)

print("Vocabulaire appris :", vectorizer.get_feature_names_out())
print()
print("Matrice de comptages (lignes = documents, colonnes = mots du vocabulaire) :")
print(vecteurs.toarray())

Vocabulaire appris : ['delivery' 'fast' 'great' 'is' 'product' 'quality' 'slow' 'the' 'was']

Matrice de comptages (lignes = documents, colonnes = mots du vocabulaire) :
[[1 0 0 0 0 0 1 1 1]
 [0 0 1 1 1 1 0 1 0]
 [3 1 0 0 0 0 0 0 1]]


#### b. TF-IDF

In [36]:
vectors, vectorizer = build_tfidf(documents)
print("Vocabulaire appris :", vectorizer.get_feature_names_out())
print()
print("Matrice TF-IDF (lignes = documents, colonnes = mots du vocabulaire) :")
print(vectors.toarray().round(3))

Vocabulaire appris : ['delivery' 'fast' 'great' 'is' 'product' 'quality' 'slow' 'the' 'was']

Matrice TF-IDF (lignes = documents, colonnes = mots du vocabulaire) :
[[0.46  0.    0.    0.    0.    0.    0.605 0.46  0.46 ]
 [0.    0.    0.467 0.467 0.467 0.467 0.    0.355 0.   ]
 [0.876 0.384 0.    0.    0.    0.    0.    0.    0.292]]


#### c.  n-grams words

In [ ]:
# affiche les n-grammes
print("N-grammes appris :", vectorizer.get_feature_names_out())
print()

print(
    "Matrice TF-IDF avec n-grammes (lignes = documents, "
    "colonnes = mots du vocabulaire) :"
)
vectors, vectorizer = build_ngram_vectorizer(
    documents, ngram_range=(1, 2), use_tfidf=True
)
print(vectors.toarray().T.round(3))

N-grammes appris : ['delivery' 'fast' 'great' 'is' 'product' 'quality' 'slow' 'the' 'was']

Matrice TF-IDF avec n-grammes (lignes = documents, colonnes = mots du vocabulaire) :
[[0.33  0.    0.649]
 [0.    0.    0.569]
 [0.33  0.    0.216]
 [0.    0.    0.284]
 [0.    0.341 0.   ]
 [0.    0.341 0.   ]
 [0.    0.341 0.   ]
 [0.    0.341 0.   ]
 [0.    0.341 0.   ]
 [0.    0.341 0.   ]
 [0.    0.341 0.   ]
 [0.434 0.    0.   ]
 [0.33  0.26  0.   ]
 [0.434 0.    0.   ]
 [0.    0.341 0.   ]
 [0.33  0.    0.216]
 [0.    0.    0.284]
 [0.434 0.    0.   ]]


#### c.  n-grams character


In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

mots = ["delivery", "delivry"]  # le second a une faute de frappe

# Vectorisation au niveau MOT (chaque mot entier = 1 unité)
vec_word = CountVectorizer(analyzer="word", token_pattern=r"(?u)\b\w+\b")
vec_word.fit(mots)
print("Vocabulaire mots :", vec_word.get_feature_names_out())
print("-> 'delivery' et 'delivry' sont 2 entrées TOTALEMENT différentes\n")

# Vectorisation au niveau CARACTERE, n-grams de 3
vec_char = CountVectorizer(analyzer="char", ngram_range=(3, 3))
vec_char.fit(mots)
vecteurs = vec_char.transform(mots).toarray()
vocab_char = vec_char.get_feature_names_out()

print("Vocabulaire caractères (3-grams) :", list(vocab_char))
print()

# Calcul du chevauchement (combien de 3-grams partagés)


v1, v2 = vecteurs[0], vecteurs[1]
chevauchement = np.minimum(v1, v2).sum()
total = min(v1.sum(), v2.sum())
print(f"3-grams partagés entre 'delivery' et 'delivry' : {chevauchement}/{total}")

Vocabulaire mots : ['delivery' 'delivry']
-> 'delivery' et 'delivry' sont 2 entrées TOTALEMENT différentes

Vocabulaire caractères (3-grams) : ['del', 'eli', 'ery', 'ive', 'ivr', 'liv', 'ver', 'vry']

3-grams partagés entre 'delivery' et 'delivry' : 3/5


In [39]:
# test de la fonction build_char_ngrams
documents = ["delivery", "delivry"]
vectors, vectorizer = build_char_ngrams(documents, ngram_range=(3, 3), use_tfidf=True)
print("Vocabulaire caractères (3-grams) :", vectorizer.get_feature_names_out())
print("Matrice TF-IDF avec 3-grams (lignes = documents, colonnes = 3-grams) :")
print(vectors.toarray().T.round(3))

Vocabulaire caractères (3-grams) : ['del' 'eli' 'ery' 'ive' 'ivr' 'liv' 'ver' 'vry']
Matrice TF-IDF avec 3-grams (lignes = documents, colonnes = 3-grams) :
[[0.335 0.379]
 [0.335 0.379]
 [0.47  0.   ]
 [0.47  0.   ]
 [0.    0.533]
 [0.335 0.379]
 [0.47  0.   ]
 [0.    0.533]]


## 2. Word2vec  

In [41]:
from embeddings.word2vec import get_word_vector, most_similar_words, train_word2vec

In [77]:
phrases_base = [
    "the delivery was fast".split(),
    "the delivery was slow".split(),
    "the shipping was fast".split(),
    "the shipping was slow".split(),
    "the delivery arrived quickly".split(),
    "the shipping arrived quickly".split(),
    "the product quality was great".split(),
    "the product quality was poor".split(),
    "customer service was helpful".split(),
    "customer service was rude".split(),
]

model_small = train_word2vec(phrases_base, vector_size=50, window=3, epochs=200)

print("Voisins de 'delivery' (corpus minuscule) :")
for mot, score in most_similar_words(model_small, "delivery", topn=30):
    print(f"  {mot:15} similarite = {score:.3f}")

print("\nVecteurs de mots :")

for mot, score in most_similar_words(model_small, "delivery", topn=2):
    print(f"  {mot:12} vector= {get_word_vector(model_small, mot).round(3)}")

Voisins de 'delivery' (corpus minuscule) :
  rude            similarite = 0.399
  slow            similarite = 0.296
  the             similarite = 0.265
  shipping        similarite = 0.250
  poor            similarite = 0.223
  product         similarite = 0.103
  arrived         similarite = 0.086
  was             similarite = 0.024
  quality         similarite = -0.008
  great           similarite = -0.029
  service         similarite = -0.045
  customer        similarite = -0.060
  helpful         similarite = -0.061
  fast            similarite = -0.180
  quickly         similarite = -0.262

Vecteurs de mots :
  rude         vector= [ 0.004  0.012  0.009 -0.015  0.014  0.001 -0.008  0.001  0.017  0.014
  0.014  0.     0.012 -0.003  0.008  0.006 -0.01  -0.011 -0.018 -0.014
 -0.003 -0.002 -0.014 -0.003  0.006 -0.011 -0.006 -0.005 -0.    -0.006
  0.01  -0.007 -0.004 -0.004 -0.013  0.008 -0.011 -0.008  0.012  0.019
  0.007  0.017  0.015 -0.001  0.011 -0.007 -0.001  0.002  0.019  0.0

In [83]:
# --- BLOC 3 : corpus repete (x50) pour simuler plus de donnees ---
phrases = phrases_base * 50

model = train_word2vec(phrases, vector_size=5, window=3, epochs=100, seed=42)

print("Voisins de 'delivery' (corpus x50) :")
for mot, score in most_similar_words(model, "delivery", topn=5):
    print(f"  {mot:12} similarite = {score:.3f}")

for mot, score in most_similar_words(model, "delivery", topn=2):
    print(f"  {mot:12} vector= {get_word_vector(model, mot).round(3)}")

print(f"  {get_word_vector(model, 'delivery').round(3)}")

cosine_similarity = np.dot(
    get_word_vector(model, "delivery"), get_word_vector(model, "shipping")
) / (
    np.linalg.norm(get_word_vector(model, "delivery"))
    * np.linalg.norm(get_word_vector(model, "shipping"))
)
print(f"Cosine similarity entre 'delivery' et 'shipping' : {cosine_similarity:.3f}")

Voisins de 'delivery' (corpus x50) :
  shipping     similarite = 0.998
  quickly      similarite = 0.955
  arrived      similarite = 0.790
  fast         similarite = 0.784
  slow         similarite = 0.769
  shipping     vector= [ 0.011  0.82   1.256  0.221 -0.301]
  quickly      vector= [-0.47   1.012  1.85   0.3   -0.715]
  [ 0.083  0.724  1.192  0.239 -0.269]
Cosine similarity entre 'delivery' et 'shipping' : 0.998


In [71]:
# --- BLOC 4 : CBOW (sg=0) vs Skip-gram (sg=1) ---
phrases_base2 = phrases_base + ["the packaging was damaged".split()]
phrases2 = phrases_base2 * 50

model_cbow = train_word2vec(
    phrases2, vector_size=50, window=3, sg=0, epochs=100, seed=42
)
model_skipgram = train_word2vec(
    phrases2, vector_size=50, window=3, sg=1, epochs=100, seed=42
)

print(
    "CBOW - voisins de 'delivery':", most_similar_words(model_cbow, "delivery", topn=3)
)
print(
    "Skip-gram - voisins de 'delivery':",
    most_similar_words(model_skipgram, "delivery", topn=3),
)
print()
print(
    "CBOW - voisins de 'packaging':",
    most_similar_words(model_cbow, "packaging", topn=3),
)
print(
    "Skip-gram - voisins de 'packaging':",
    most_similar_words(model_skipgram, "packaging", topn=3),
)

CBOW - voisins de 'delivery': [('shipping', 0.9970637559890747), ('arrived', 0.89862459897995), ('quickly', 0.8766067624092102)]
Skip-gram - voisins de 'delivery': [('shipping', 0.9961312413215637), ('quickly', 0.8454437851905823), ('arrived', 0.8291676640510559)]

CBOW - voisins de 'packaging': [('damaged', 0.7437599301338196), ('was', 0.704200267791748), ('slow', 0.6906068325042725)]
Skip-gram - voisins de 'packaging': [('damaged', 0.6933912038803101), ('was', 0.6412721276283264), ('quality', 0.6330041289329529)]


In [72]:
# --- BLOC 5 : similarite entre mots relies vs mots sans rapport ---
print("Mots relies (contextes similaires) :")
print("  delivery <-> shipping :", model.wv.similarity("delivery", "shipping"))
print()
print("Mots sans rapport apparent :")
print("  delivery <-> rude     :", model.wv.similarity("delivery", "rude"))
print("  delivery <-> helpful  :", model.wv.similarity("delivery", "helpful"))

Mots relies (contextes similaires) :
  delivery <-> shipping : 0.9964196

Mots sans rapport apparent :
  delivery <-> rude     : 0.22653265
  delivery <-> helpful  : 0.23043983


In [73]:
# --- BLOC 6 : effet de vector_size (dimensionnalite) ---
# Verifie aussi test_word_vector_has_correct_dimension()
for size in [10, 50, 200]:
    m = train_word2vec(phrases, vector_size=size, window=3, epochs=100, seed=42)
    top1 = most_similar_words(m, "delivery", topn=1)[0]
    vecteur = get_word_vector(m, "delivery")
    print(f"vector_size={size:4} -> voisin : {top1}  |  dimension : {vecteur.shape}")

vector_size=  10 -> voisin : ('shipping', 0.9896082878112793)  |  dimension : (10,)
vector_size=  50 -> voisin : ('shipping', 0.9964196681976318)  |  dimension : (50,)
vector_size= 200 -> voisin : ('shipping', 0.9983150959014893)  |  dimension : (200,)


In [50]:
# --- BLOC 7 : effet de window (taille du contexte) ---
for w in [1, 3, 10]:
    m = train_word2vec(phrases, vector_size=50, window=w, epochs=100, seed=42)
    top1 = most_similar_words(m, "delivery", topn=1)[0]
    print(f"window={w:2} -> voisin le plus proche de 'delivery' : {top1}")

window= 1 -> voisin le plus proche de 'delivery' : ('shipping', 0.9937880635261536)
window= 3 -> voisin le plus proche de 'delivery' : ('shipping', 0.9964196681976318)
window=10 -> voisin le plus proche de 'delivery' : ('shipping', 0.9969074726104736)


## 3. FastText  

In [84]:
from gensim.models import FastText, Word2Vec

phrases_base = [
    "the delivery was fast".split(),
    "the delivery was slow".split(),
    "the shipping was fast".split(),
    "the shipping was slow".split(),
    "the delivery arrived quickly".split(),
    "the shipping arrived quickly".split(),
    "the product quality was great".split(),
    "the product quality was poor".split(),
    "customer service was helpful".split(),
    "customer service was rude".split(),
] * 50

model_w2v = Word2Vec(
    sentences=phrases_base,
    vector_size=50,
    window=3,
    min_count=1,
    sg=1,
    epochs=100,
    seed=42,
)
model_ft = FastText(
    sentences=phrases_base,
    vector_size=50,
    window=3,
    min_count=1,
    sg=1,
    epochs=100,
    seed=42,
)

mot_jamais_vu = "deliveryyy"  # n'existe dans AUCUNE phrase du corpus

print(
    "Le mot",
    repr(mot_jamais_vu),
    "existe dans le corpus ?",
    mot_jamais_vu in " ".join([" ".join(p) for p in phrases_base]),
)
print()

print("--- Word2Vec sur un mot jamais vu ---")
try:
    vecteur = model_w2v.wv[mot_jamais_vu]
    print("Vecteur obtenu :", vecteur[:5])
except KeyError as e:
    print("ECHEC :", e)

print()
print("--- FastText sur le meme mot jamais vu ---")
try:
    vecteur = model_ft.wv[mot_jamais_vu]
    print("Vecteur obtenu (5 premieres valeurs) :", vecteur[:5].round(3))
    print(
        "Voisins les plus proches de ce mot inconnu :",
        model_ft.wv.most_similar(mot_jamais_vu, topn=3),
    )
except KeyError as e:
    print("ECHEC :", e)

Le mot 'deliveryyy' existe dans le corpus ? False

--- Word2Vec sur un mot jamais vu ---
ECHEC : "Key 'deliveryyy' not present"

--- FastText sur le meme mot jamais vu ---
Vecteur obtenu (5 premieres valeurs) : [-0.159 -0.107  0.192 -0.125 -0.086]
Voisins les plus proches de ce mot inconnu : [('delivery', 0.9999302625656128), ('shipping', 0.9974160194396973), ('quickly', 0.990179717540741)]


In [4]:
# --- BLOC 1 : imports ---
import os
import sys

sys.path.insert(0, os.path.abspath("../src"))

from embeddings.fastText import (
    get_word_vector,
    is_out_of_vocabulary,
    most_similar_words,
    train_fasttext,
)
from embeddings.word2vec import most_similar_words as most_similar_words_w2v
from embeddings.word2vec import train_word2vec

In [5]:
# --- BLOC 2 : entrainement de base ---
phrases_base = [
    "the delivery was fast".split(),
    "the delivery was slow".split(),
    "the shipping was fast".split(),
    "the shipping was slow".split(),
    "the delivery arrived quickly".split(),
    "the shipping arrived quickly".split(),
] * 50

model_ft = train_fasttext(phrases_base, vector_size=50, window=3, epochs=100)

print("Voisins de 'delivery' :")
for mot, score in most_similar_words(model_ft, "delivery", topn=3):
    print(f"  {mot:12} similarite = {score:.3f}")

Voisins de 'delivery' :
  shipping     similarite = 1.000
  quickly      similarite = 0.999
  arrived      similarite = 0.999


In [6]:
# --- BLOC 3 : LA difference cle avec Word2Vec -- mot jamais vu (OOV) ---
mot_inconnu = "deliveryyy"  # n'existe dans AUCUNE phrase du corpus

print(
    f"'{mot_inconnu}' est hors-vocabulaire :",
    is_out_of_vocabulary(model_ft, mot_inconnu),
)

# FastText : doit fonctionner
vecteur_ft = get_word_vector(model_ft, mot_inconnu)
print("FastText - vecteur obtenu, dimension :", vecteur_ft.shape)
print(
    "FastText - voisins de ce mot inconnu :",
    most_similar_words(model_ft, mot_inconnu, topn=2),
)

# Word2Vec sur le meme mot -- doit planter (KeyError), c'est attendu
model_w2v = train_word2vec(phrases_base, vector_size=50, window=3, epochs=100)
try:
    most_similar_words_w2v(model_w2v, mot_inconnu, topn=2)
    print("Word2Vec - PAS d'erreur (inattendu)")
except KeyError as e:
    print("Word2Vec - echec attendu :", e)

'deliveryyy' est hors-vocabulaire : True
FastText - vecteur obtenu, dimension : (50,)
FastText - voisins de ce mot inconnu : [('delivery', 0.9999325275421143), ('shipping', 0.999801516532898)]
Word2Vec - echec attendu : "Key 'deliveryyy' not present in vocabulary"


In [7]:
# --- BLOC 4 : effet de min_n / max_n (taille des n-grams de caracteres) ---
# min_n/max_n plus petits -> capture des fragments plus courts (plus de bruit,
# mais plus de chevauchement possible avec des mots courts)
# min_n/max_n plus grands -> fragments plus longs, plus specifiques

for min_n, max_n in [(2, 4), (3, 6), (4, 8)]:
    m = train_fasttext(
        phrases_base, vector_size=50, window=3, epochs=100, min_n=min_n, max_n=max_n
    )
    vecteur = get_word_vector(m, mot_inconnu)
    voisin = most_similar_words(m, mot_inconnu, topn=1)[0]
    print(f"min_n={min_n}, max_n={max_n} -> voisin de '{mot_inconnu}' : {voisin}")

min_n=2, max_n=4 -> voisin de 'deliveryyy' : ('delivery', 0.9999638795852661)
min_n=3, max_n=6 -> voisin de 'deliveryyy' : ('delivery', 0.9999325275421143)
min_n=4, max_n=8 -> voisin de 'deliveryyy' : ('delivery', 0.9998621344566345)


In [8]:
# --- BLOC 5 : rejouer les assertions du fichier de tests, a la main ---
assert is_out_of_vocabulary(model_ft, "deliveryyy") is True
assert is_out_of_vocabulary(model_ft, "delivery") is False
print("OK : is_out_of_vocabulary() distingue bien mot connu / inconnu")

neighbors = most_similar_words(model_ft, "deliveryyy", topn=1)
assert neighbors[0][0] == "delivery"
assert neighbors[0][1] > 0.9
print("OK : le mot deforme reste bien le plus proche de sa racine")

OK : is_out_of_vocabulary() distingue bien mot connu / inconnu
OK : le mot deforme reste bien le plus proche de sa racine


## 4. Glove  

In [4]:
import numpy as np


def load_glove(path):
    embeddings = {}

    with open(path, encoding="utf-8") as f:
        for line in f:
            values = line.split()
            word = values[0]
            vector = np.asarray(values[1:], dtype="float32")
            embeddings[word] = vector

    return embeddings


glove = load_glove("../data/external/glove.6B.100d.txt")

print(f"Vocabulary size: {len(glove)}")
print(f"Embedding dimension: {len(next(iter(glove.values())))}")

Vocabulary size: 400000
Embedding dimension: 100


In [5]:
word = "excellent"

vector = glove[word]

print("Word:", word)
print("Vector shape:", vector.shape)
print("First 10 values:", vector[:10])

Word: excellent
Vector shape: (100,)
First 10 values: [-0.2816    0.18427  -0.06755   0.27694  -0.066775 -0.41389   0.30757
 -0.11097  -0.84585  -0.17047 ]


In [6]:
from sklearn.metrics.pairwise import cosine_similarity


def most_similar(word, embeddings, top_n=5):
    target = embeddings[word].reshape(1, -1)

    words = list(embeddings.keys())
    matrix = np.array([embeddings[w] for w in words])

    similarities = cosine_similarity(target, matrix)[0]
    indices = np.argsort(similarities)[::-1][1 : top_n + 1]

    return [(words[i], similarities[i]) for i in indices]


most_similar("excellent", glove)

[('good', np.float32(0.7936238)),
 ('quality', np.float32(0.7606268)),
 ('terrific', np.float32(0.7415625)),
 ('superb', np.float32(0.7402959)),
 ('best', np.float32(0.72875696))]

In [7]:
def sentence_embedding(tokens, embeddings):
    vectors = [embeddings[token] for token in tokens if token in embeddings]

    if not vectors:
        return np.zeros(len(next(iter(embeddings.values()))))

    return np.mean(vectors, axis=0)


tokens = ["the", "product", "is", "excellent"]

sentence_vector = sentence_embedding(tokens, glove)

print("Sentence embedding shape:", sentence_vector.shape)

Sentence embedding shape: (100,)


In [ ]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

words = ["good", "great", "excellent", "bad", "terrible", "awful"]

vectors = np.array([glove[word] for word in words])

coords = PCA(n_components=2).fit_transform(vectors)

plt.figure(figsize=(8, 6))
plt.scatter(coords[:, 0], coords[:, 1])

for i, word in enumerate(words):
    plt.annotate(word, coords[i])

plt.title("GloVe Word Embeddings")
plt.show()

In [17]:
import os
import sys

sys.path.insert(0, os.path.abspath("../src"))

from embeddings.glove import (
    get_word_vector,
    is_in_vocabulary,
    load_glove_from_file,
    most_similar_words,
)

# Option A : telechargement automatique via gensim (utilise dans les blocs suivants)
# model = load_pretrained_glove("glove-50")
# print("Vocabulaire charge :", len(model.key_to_index), "mots")

# Option B : si tu as deja glove.6B.50d.txt / 100d / 200d / 300d telecharge
model = load_glove_from_file("../data/external/glove.6B.300d.txt")

In [18]:
# --- BLOC 2 : voisins de mots -- sur un VRAI corpus, pas notre jouet ---
print("Voisins de 'delivery' :", most_similar_words(model, "delivery", topn=5))
print("Voisins de 'happy' :", most_similar_words(model, "happy", topn=5))
print("Voisins de 'terrible' :", most_similar_words(model, "terrible", topn=5))

Voisins de 'delivery' : [('deliveries', 0.652673065662384), ('crude', 0.48354148864746094), ('delivering', 0.48306146264076233), ('cents', 0.46360641717910767), ('deliver', 0.4457153081893921)]
Voisins de 'happy' : [("'m", 0.7080122232437134), ('glad', 0.6905031800270081), ('pleased', 0.6712467074394226), ('really', 0.6575899124145508), ('always', 0.6494665741920471)]
Voisins de 'terrible' : [('horrible', 0.8621524572372437), ('awful', 0.7882837653160095), ('dreadful', 0.7239290475845337), ('horrendous', 0.6983873844146729), ('horrific', 0.6624177098274231)]


In [19]:
# --- BLOC 3 : la limite face a un mot inconnu (contrairement a FastText) ---
mot_invente = "asdkjfhaslkdjfh12345"
print(f"'{mot_invente}' dans le vocabulaire :", is_in_vocabulary(model, mot_invente))
try:
    get_word_vector(model, mot_invente)
except KeyError as e:
    print("Echec attendu (pas de mecanisme n-grams comme FastText) :", e)

'asdkjfhaslkdjfh12345' dans le vocabulaire : False
Echec attendu (pas de mecanisme n-grams comme FastText) : "Key 'asdkjfhaslkdjfh12345' not present"


In [23]:
# --- BLOC 4 : comparer GloVe vs notre FastText jouet sur le meme mot connu ---
from embeddings.fastText import most_similar_words as most_similar_words_ft
from embeddings.fastText import train_fasttext

phrases_jouet = [
    "the delivery was fast".split(),
    "the delivery was slow".split(),
    "the shipping was fast".split(),
    "the shipping was slow".split(),
] * 50
model_ft_jouet = train_fasttext(phrases_jouet, vector_size=50, window=3, epochs=100)

print("\nVoisins de 'delivery' selon GloVe (corpus reel, milliards de mots) :")
print(most_similar_words(model, "delivery", topn=3))
print("Voisins de 'delivery' selon notre FastText jouet (corpus minuscule) :")
print(most_similar_words_ft(model_ft_jouet, "delivery", topn=3))
# a retenir : GloVe donne des voisins varies et nuances (vrai corpus),
# notre FastText jouet ne connait que les quelques mots de son petit corpus


# --- BLOC 5 : rejouer les assertions du fichier de tests, a la main ---
assert len(model.key_to_index) > 100_000
print("OK : vocabulaire bien superieur a 100 000 mots")

vecteur = get_word_vector(model, "delivery")
assert vecteur.shape == (300,)
print("OK : dimension du vecteur correcte")


Voisins de 'delivery' selon GloVe (corpus reel, milliards de mots) :
[('deliveries', 0.652673065662384), ('crude', 0.48354148864746094), ('delivering', 0.48306146264076233)]
Voisins de 'delivery' selon notre FastText jouet (corpus minuscule) :
[('shipping', 0.9995194673538208), ('fast', 0.9989628195762634), ('slow', 0.9986440539360046)]
OK : vocabulaire bien superieur a 100 000 mots
OK : dimension du vecteur correcte


## 5. Contextual embeddings


In [24]:
# --- BLOC 1 : imports ---

from embeddings.contextual_embeddings import (
    compare_sentence_models,
    cross_lingual_similarity_test,
    get_contextual_word_vectors,
    get_sentence_embeddings,
    sentence_similarity,
)

# --- BLOC 2 : sentence embeddings -- un vecteur par phrase entiere ---
phrases = [
    "The delivery was fast and the product is great",
    "Shipping arrived quickly, excellent item",
    "The website checkout process was confusing",
]

embeddings = get_sentence_embeddings(phrases)
print("Dimension par phrase :", embeddings.shape)

sim_proches = sentence_similarity(phrases[0], phrases[1])
sim_eloignees = sentence_similarity(phrases[0], phrases[2])
print(f"Similarite (phrases 1 et 2, semantiquement proches) : {sim_proches:.3f}")
print(f"Similarite (phrases 1 et 3, sujets differents)      : {sim_eloignees:.3f}")

/home/ensai/Documents/Repositories_Git/sentiment-analysis-platform/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6904.59it/s]


Dimension par phrase : (3, 384)


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4147.91it/s]


Similarite (phrases 1 et 2, semantiquement proches) : 0.696
Similarite (phrases 1 et 3, sujets differents)      : 0.288


In [ ]:
# --- BLOC 3 : contextual embeddings -- le meme mot, deux sens differents ---
import numpy as np

phrase_a = "I sat by the river bank"
phrase_b = "I deposited money at the bank"

vecteurs_a = get_contextual_word_vectors(phrase_a)
vecteurs_b = get_contextual_word_vectors(phrase_b)

vec_bank_a = vecteurs_a["bank"]
vec_bank_b = vecteurs_b["bank"]

diff = np.linalg.norm(vec_bank_a - vec_bank_b)
print(f"Difference entre les deux vecteurs de 'bank' : {diff:.4f}")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5920.29it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4120.51it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 

Difference entre les deux vecteurs de 'bank' : 10.4444


In [33]:
vecteurs_a.keys()

dict_keys(['[CLS]', 'i', 'sat', 'by', 'the', 'river', 'bank', '[SEP]'])

In [ ]:
# --- BLOC 4 : comparaison multi-modeles (dimension, vitesse) ---
resultats = compare_sentence_models(phrases)
for nom, stats in resultats.items():
    print(
        f"  {nom:45} dimension={stats['dimension']:4}  \
            temps={stats['encode_time_seconds']}s"
    )


# --- BLOC 5 : test multilingue -- le plus important pour ce projet (EN/ES/DE/HI/FR) ---
phrase_en = "The delivery was fast and the packaging was excellent"
phrase_fr = "La livraison etait rapide et l'emballage etait excellent"

print("Modele anglais-seul (attendu : score plus bas) :")
score_monolingue = cross_lingual_similarity_test(
    "all-MiniLM-L6-v2", phrase_en, phrase_fr
)
print(f"  Similarite EN/FR : {score_monolingue:.3f}")

print("Modele multilingue (attendu : score nettement plus haut) :")
score_multilingue = cross_lingual_similarity_test(
    "paraphrase-multilingual-MiniLM-L12-v2", phrase_en, phrase_fr
)
print(f"  Similarite EN/FR : {score_multilingue:.3f}")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5898.95it/s]


  all-MiniLM-L6-v2                              dimension= 384  temps=0.0228s
  all-mpnet-base-v2                             dimension= 768  temps=0.0527s
  paraphrase-multilingual-MiniLM-L12-v2         dimension= 384  temps=0.0986s
Modele anglais-seul (attendu : score plus bas) :


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3806.72it/s]


  Similarite EN/FR : 0.220
Modele multilingue (attendu : score nettement plus haut) :


Loading weights: 100%|██████████| 199/199 [00:00<00:00, 14288.32it/s]


  Similarite EN/FR : 0.923
